name: aulajaja
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  flutter_lints: ^4.0.0
  cloud_firestore: ^4.17.5

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/AulajajaLogo.png
